AYASOMPO_SMSGatewayV2/Models/FireUWViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AYASOMPO_SMSGatewayV2.Models
{
    public class FireUWViewModel
    {
        public Guid Id { get; set; }
        public string ReferenceNo { get; set; }
        public string Class { get; set; }
        public string ProductCode { get; set; }
        public DateTime? IssueDate { get; set; }
        public string ProposalNo { get; set; }
        public string DrsreferenceNo { get; set; }
        public string TransactionType { get; set; }
        public string CusCode { get; set; }
        public string CusName { get; set; }
        public string IntermediaryCode { get; set; }
        public byte[] IntermediaryName { get; set; }
        public string AgentCode { get; set; }
        public string AgentName { get; set; }
        public string AccountCode { get; set; }
        public string AccountUserCode { get; set; }
        public string AccountHandlerCode { get; set; }
        public decimal? TotalSumInsured { get; set; }
        public decimal? Premium { get; set; }
        public DateTime? PolicyStartDate { get; set; }
        public DateTime? PolicyEndDate { get; set; }
        public DateTime? UwsubmittedDate { get; set; }
        public string Uwstatus { get; set; }
        public DateTime? UwstatusDate { get; set; }
        public string Uwremark { get; set; }
        public int? Version { get; set; }

        public string MailingAddress { get; set; }

        public List<RiskLocation> lstRiskLocations = new List<RiskLocation>();

        public FireConstruction fireConstruction = new FireConstruction();
        public FireRiskdetail fireRiskdetail = new FireRiskdetail();
        public FireFeaInfo fireFeaInfo = new FireFeaInfo();
        public FireFirewatertank fireFirewatertank = new FireFirewatertank();
        public FireSecurity fireSecurity = new FireSecurity();
        public FireInventoryinfo fireInventoryinfo = new FireInventoryinfo();
        public FireCoverageinfo fireCoverageinfo = new FireCoverageinfo();
        
        public int riskCount { get; set; }

    }
}

AYASOMPO_SMSGatewayV2/Controllers/FireRuleBaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using AYASOMPO_SMSGatewayV2.Models;
using AYASOMPO_SMSGatewayV2.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Rewrite.Internal.ApacheModRewrite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Rotativa.AspNetCore;
using static AYASOMPO_SMSGatewayV2.Models.CustomerInfoViewModel;
using static AYASOMPO_SMSGatewayV2.Models.DefaultPolicyAnswerResponse;
using static AYASOMPO_SMSGatewayV2.Models.FireProposalViewModel;

namespace AYASOMPO_SMSGatewayV2.Controllers
{
    public class FireRuleBaseController : Controller
    {
        IILAPIservices IILAPIservices = new IILAPIservices();
        List<QuestionRule> lstQuestionRule = new List<QuestionRule>();
        MiddlewareAPIService _middlewareAPI = new MiddlewareAPIService();
        MainDBContext _context = new MainDBContext();
        private IHostingEnvironment _env;
        private IConfiguration _configuration;
        public IConfiguration Configuration { get; set; }
        private HttpClient _client;
        FireRuleValidation ruleValidation = new FireRuleValidation();
        public string sqlCon { get; set; }
        public ISession session;

        #region static master list
        List<MasterDataViewModel> lstOccupancy = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstRoof = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstWalls = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstColumns = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstFloor = new List<MasterDataViewModel>();

        List<MasterDataViewModel> lstABCType = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstCO2Type = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstExtinguisher = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstWeightOfFire = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstRequiredNumberOfExtinguisher = new List<MasterDataViewModel>();

        List<MasterDataViewModel> lstHoseReel = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstHydrant = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstTypeFireTank = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstNumberOfFireTank = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstSecurityGuardsData = new List<MasterDataViewModel>();

        List<MasterDataViewModel> lstSecurityGuardsDutyShiftData = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstSecurityGuardsDutyHourData = new List<MasterDataViewModel>();
        List<MasterDataViewModel> lstNumberOfCCTVData = new List<MasterDataViewModel>();
        List<ProductClassViewModel> lstProductClassViewModels = new List<ProductClassViewModel>();
        List<InventoryItemByPCodeViewModel> lstInventoryItemByPCodeViewModels = new List<InventoryItemByPCodeViewModel>();

        List<AgentCodeMaster> lstAgentCode = new List<AgentCodeMaster>();
        List<AccountCodeMaster> lstAccountCode = new List<AccountCodeMaster>();
        List<IntemediaryViewModel> lstIntemediaryViewModels = new List<IntemediaryViewModel>();
        List<MasterDataViewModel> lstClassOfBuilding = new List<MasterDataViewModel>();


        #endregion

        public enum Operator
        {
            Equal,
            NotEqual,
            AllowStatus,
            String,
            Number
        }

        public enum PriorityLevel
        {
            level1 = 1,
            level2 = 2,
            level3 = 3,
            level4 = 4,
            level5 = 5,

            level6 = 6,
            level7 = 7,
            level8 = 8,
            level9 = 9,
            level10 = 10,

            level11 = 11,
            level12 = 12,
            level13 = 13,
            level14 = 14,
            level15 = 15,

            level16 = 16,
            level17 = 17,
            level18 = 18,
            level19 = 19,
            level20 = 20,


            level21 = 21,
            level22 = 22,
            level23 = 23,
            level24 = 24,
            level25 = 25,

            level26 = 26,
            level27 = 27,
            level28 = 28,
            level29 = 29,
            level30 = 30,

            level31 = 31,
            level32 = 32,
            level33 = 33,
            level34 = 34,
            level35 = 35,

            level36 = 36,
            level37 = 37,
            level38 = 38,
            level39 = 39,
            level40 = 40,

            level41 = 41,
            level42 = 42,
            level43 = 43,
            level44 = 44,
            level45 = 45,

            level46 = 46,
            level47 = 47,
            level48 = 48,
            level49 = 49,
            level50 = 50

        }

        public enum TransactionType
        {
            New,
            Renewal
        }

        public FireRuleBaseController(IHostingEnvironment env, IConfiguration configuration)
        {
            _env = env;
            _configuration = configuration;
            _client = new HttpClient();

            var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
             .AddJsonFile("appsettings.json");
            Configuration = builder.Build();

            sqlCon = Configuration["ConnectionStrings:DefaultConnection"].ToString();

        }

        public IActionResult Test()
        {
            return View();
        }

       
        public async Task<IActionResult> FireUW()
        {
            PrepareData();
            await PrepareDataMasterDataAsync();
            FireUWViewModel fireUWViewModel = new FireUWViewModel();
            if (HttpContext.Session.GetObjectFromJson<List<RiskLocation>>("lstRiskLocations") != null)
            {
                List<RiskLocation> lstRiskLocations = new List<RiskLocation>();
                lstRiskLocations = HttpContext.Session.GetObjectFromJson<List<RiskLocation>>("lstRiskLocations");

                if (lstRiskLocations.Count() > 0)
                {
                    fireUWViewModel.lstRiskLocations = lstRiskLocations;
                    //fireUWViewModel.riskCount = lstRiskLocations.Count();
                    var risk = (from d in lstRiskLocations
                                orderby d.RiskName
                                select d.RiskName).ToList().Distinct();
                    decimal tsi = 0;
                    tsi = Convert.ToDecimal(lstRiskLocations.Sum(t => t.RiskSumInsured));
                    fireUWViewModel.TotalSumInsured = tsi;

                    fireUWViewModel.riskCount = (from d in lstRiskLocations
                                                 orderby d.RiskName
                                                 select d.RiskName).ToList().Distinct().Count();
                    
                }
            }
            return View(fireUWViewModel);
        }

        public async Task<ActionResult> EditFireUW(string refNo)
        {
            PrepareData();
            await PrepareDataMasterDataAsync();
            FireRuleProposalViewModel fireRuleProposalViewModel = new FireRuleProposalViewModel();
            fireRuleProposalViewModel = GetFireProposalrelatedData(refNo);
            fireRuleProposalViewModel.riskCount = fireRuleProposalViewModel.fireRiskdetails.Count;

            return View(fireRuleProposalViewModel);
        }

        #region Post to UW Request
        public ActionResult PostToUW(string refNo)
        {
            PrepareData();
            RequestDetailViewModel requestDetailViewModel = new RequestDetailViewModel();
            requestDetailViewModel.ReferenceNo = refNo;
            requestDetailViewModel.lstFireRequireddocumentsetting = _context.FireRequireddocumentsetting.ToList();
            return View(requestDetailViewModel);
        }

        public ActionResult SummaryRequestView(string refNo)
        {

            RequestDetailViewModel requestDetailViewModel = new RequestDetailViewModel();
            if (refNo != null)
            {

            }

            return View();
        }

        public ActionResult SaveRequestDetail(RequestDetailViewModel requestDetailViewModel)
        {
            try
            {
                Requestdetail requestdetail = new Requestdetail();
                if (requestDetailViewModel.ReferenceNo != null)
                {
                    UwPerson uwPerson = new UwPerson();
                    requestdetail.Id = Guid.NewGuid();
                    requestdetail.ProposalReferenceNo = requestDetailViewModel.ReferenceNo;
                    requestdetail.UwpersonId = requestDetailViewModel.UwpersonId;
                    if (requestdetail.UwpersonId != null)
                    {
                        uwPerson = _context.UwPerson.Where(uw => uw.Id == requestdetail.UwpersonId).FirstOrDefault();
                    }
                    requestdetail.UwpersonEmail = uwPerson.PersonEmail;
                    requestdetail.RequestedDate = DateTime.Now;
                    requestdetail.Status = "pending";
                    requestdetail.Buremark = requestDetailViewModel.Buremark;

                    _context.Entry(requestdetail).State = EntityState.Added;
                    _context.SaveChanges();

                    #region Save Files to RequiredDocuments Upload and Approval Form

                    FireRequireddocuments fireRequireddocuments = new FireRequireddocuments();

AYASOMPO_SMSGatewayV2/Views/FireRuleBase/FireRuleSetup.cshtml
@model RuleViewModel
@{
    ViewData["Title"] = "FireRuleSetup";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script src="~/js/rule.js"></script>
<link href="~/css/select2/css/select2.min.css" rel="stylesheet" />
<script src="~/css/select2/js/select2.min.js"></script>

<script type="text/javascript">
    $('document').ready(function () {

        //   onload: call the above function
        $(".select2").each(function () {
            initializeSelect2($(this));
        });

        $(".select2").select2({
            allowClear: true,
            tags: true,
            width: 'resolve' // need to override the changed default
        });


    });

    //function to initialize select2
    function initializeSelect2(selectElementObj) {
        selectElementObj.select2({
            //tags: false,
            allowClear: true,
        });
    }

</script>

<div class="row">
    <div class="col-md-12">
        <div class="x_content">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Fire Rule Base Setup<small></small></h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>

                                <li>
                                    <a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        @using (Html.BeginForm("SaveFireRule", "FireRuleBase", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="x_content">
                                <div class="form-horizontal form-label-left">
                                    <div class="form-group row">
                                        <div class="col-md-9 col-sm-9  offset-md-3">
                                            <button type="button" class="btn btn-primary">Cancel</button>
                                            <button class="btn btn-primary" type="reset">Reset</button>
                                            <button type="submit" class="btn btn-success">Save</button>
                                        </div>
                                    </div>

                                    <div class="ln_solid"></div>

                                    <div class="form-group row">
                                        <label class="control-label col-md-3 col-sm-3" style="font-weight:700;">If the following conditions are met</label>
                                    </div>


                                    <div class="form-group row">
                                        <label class="control-label col-md-3 col-sm-3 ">Your Mean Preference</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            @Html.DropDownListFor(model => model.QuestionId1, ViewBag.RuleQuestion1 as IEnumerable<SelectListItem>, "Your Mean Preference", new { @class = "form-control select2", @id = "ddlQuestionId1" })
                                        </div>
                                    </div>

                                    <div class="form-group row" id="divOperation">
                                        <label class="control-label col-md-3 col-sm-3 ">Operator</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            @Html.DropDownListFor(model => model.Operator1, ViewBag.OperatorList as IEnumerable<SelectListItem>, "Select Compare Operator", new { @class = "form-control select2" })
                                        </div>
                                    </div>


                                    <!-- Add Additional rule (AND) -->

                                    <div class="form-group row" id="divTextBox2">
                                        <label class="control-label col-md-3 col-sm-3 ">Your Custom Value</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            <input type="text" class="form-control" placeholder="Your Custom Value" asp-for="Value1" />
                                        </div>
                                    </div>

                                    <div class="form-group row" id="divQuestion2">
                                        <label class="control-label col-md-3 col-sm-3 ">Your Mean Value 2</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            <select id="ddlValue1" class="form-control" asp-for="Value1">
                                                <option value="">Choose Value</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>

                                    <div class="form-group row" style="margin-top:10px;">
                                        <label class="control-label col-md-3 col-sm-3 "></label>
                                        <div class="col-md-9 col-sm-9">
                                            <input type="button" value="Add Condition" class="btn btn-primary" id="btnRuleAdd" />

                                            <div class="row" style="border: 1px solid #aeabab;padding:20px;margin-top:20px;" id="divAdditionalRule">
                                                <div class="form-group row">
                                                    <label class="control-label col-md-3 col-sm-3 ">Your Mean Preference 3</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        @Html.DropDownListFor(model => model.QuestionId2, ViewBag.RuleQuestion1 as IEnumerable<SelectListItem>, "Your Mean Preference", new { @class = "form-control", @id = "ddlQuestionId3" })
                                                    </div>
                                                </div>

                                                <div class="form-group row" id="divOperation">
                                                    <label class="control-label col-md-3 col-sm-3 ">Operator</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        @Html.DropDownListFor(model => model.Operator2, ViewBag.OperatorList as IEnumerable<SelectListItem>, "Select Compare Operator", new { @class = "form-control" })
                                                    </div>
                                                </div>

                                                <div class="form-group row" id="divQuestion3">
                                                    <label class="control-label col-md-3 col-sm-3 ">Your Mean Value 4</label>
                                                    <div class="col-md-9 col-sm-9 ">
                                                        <select id="ddlValue2" class="form-control" asp-for="Value2">
                                                            <option value="">Choose Value</option>
                                                        </select>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>

                                    </div>


                                    <div class="form-group row">
                                        <label class="control-label col-md-3 col-sm-3" style="font-weight:700;">Perform the following action</label>
                                    </div>

                                    <div class="form-group row">
                                        <label class="control-label col-md-3 col-sm-3 ">Priority Level</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            @Html.DropDownListFor(model => model.Priority, ViewBag.PriorityList as IEnumerable<SelectListItem>, "Priority", new { @class = "form-control ddlMultipleSelect" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="control-label col-md-3 col-sm-3 ">Your Actions</label>
                                        <div class="col-md-9 col-sm-9 ">
                                            @Html.DropDownListFor(model => model.Action, ViewBag.lstRuleActions as IEnumerable<SelectListItem>, "Your Action", new { @class = "form-control select2" })
                                        </div>
                                    </div>

                                </div>


                            </div>
                        }

                        @if (ViewBag.lstRules != null)
                        {
                            <div class="card-box table-responsive">
                                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Preference1 Name</th>
                                            <th>Preference1 Value</th>
                                            <th>Preference2 Name</th>
                                            <th>Preference2 Value</th>
                                            <th>Priority Level</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var rule in (List<Rules>)ViewBag.lstRules)
                                        {
                                            <tr>
                                               
                                                <td style="width:50px;">
                                                    <a href='@Url.Action("DeleteRule", "FireRuleBase", new { @Id = @rule.Id })'>
                                                        <span class="fa fa-trash ayascolor"></span>
                                                    </a>
                                                </td>

                                                <td style="width:100px;">@rule.Preference1_Name</td>
                                                <td style="width:300px;">@rule.Value1</td>
                                                <td style="width:100px;">@rule.Preference2_Name</td>
                                                <td style="width:300px;">@rule.Value2</td>
                                                <td style="width:100px;">@rule.PriorityLevel</td>
                                                <td style="width:300px;">@rule.Action</td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>

                        }

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

AYASOMPO_SMSGatewayV2/Views/FireRuleBase/RiskLocationUpload.cshtml
@model RiskLocationViewModel
@{
    ViewData["Title"] = "RiskLocationUpload";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script src="~/js/fire.js"></script>

<style>
    #custom-button {
        padding: 10px;
        color: #495057;
        border: 1px solid #ced4da;
        border-radius: 5px;
        cursor: pointer;
    }

        #custom-button:hover {
        }

    #custom-text {
        margin-left: 10px;
        font-family: sans-serif;
        color: #aaa;
    }
</style>

<script>

    $(function () {
        $(".monthpicker").datetimepicker({
            format: "MMM/YYYY"
        });
    });



    $(document).ready(function () {
        
        const realFileBtn = document.getElementById("Files");
        const customBtn = document.getElementById("custom-button");
        const customTxt = document.getElementById("custom-text");

        customBtn.addEventListener("click", function () {
            realFileBtn.click();
        });

        realFileBtn.addEventListener("change", function () {
            if (realFileBtn.value) {
                customTxt.innerHTML = realFileBtn.value.match(
                    /[\/\\]([\w\d\s\.\-\(\)]+)$/
                )[1];
            } else {
                customTxt.innerHTML = "No file chosen, yet.";
            }
        });

    });



</script>

<div class="row">
    <div class="col-md-12">
        <div class="x_content">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Fire Policy Creation<small></small></h2>

                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="btn btn-app" href='@Url.Action("FireUW", "FireRuleBase")'>
                                        <i class="fa fa-plus"></i> Start
                                    </a>
                                </li>

                                <li>
                                    <a class="btn btn-app" href='@Url.Action("RiskLocationUpload", "FireRuleBase")'>
                                        <i class="fa fa-repeat"></i> Reset
                                    </a>
                                </li>

                            </ul>
                            <div class="clearfix"></div>
                        </div>

                        <div class="col-md-12 col-sm-12">
                            <div class="x_content">
                                @using (Html.BeginForm("Upload", "FireRuleBase", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    <div class="form-horizontal form-label-left">
                                        <div class="form-group row ">
                                            <label class="control-label col-md-3 col-sm-3 ">Risk Location Upload</label>
                                            <div class="col-md-9 col-sm-9">
                                                @*<input type="file" id="Files" name="Files" hidden="hidden" onchange="uploadFiles('real-file');" />*@
                                                <input type="file" id="Files" name="Files" hidden="hidden" />
                                                <button type="button" id="custom-button">
                                                    Browse Location list file
                                                </button>
                                                <span id="custom-text">No file chosen, yet.</span>

                                                <button type="submit" class="btn btn-success">
                                                    <i class="fa fa-upload"></i>
                                                    Upload
                                                </button>
                                            </div>
                                        </div>

                                    </div>

                                }
                            </div>
                        </div>

                        @if (ViewBag.lstRiskLocation != null)
                        {
                            <div class="col-md-12 col-sm-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                        <h2>Location Detail</h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                            <li>
                                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                            </li>

                                        </ul>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="x_content">

                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>RiskName</th>
                                                    <th>Building No</th>
                                                    <th>Street</th>
                                                    <th>Ward</th>
                                                    <th>Town</th>
                                                    <th>Township</th>
                                                    <th>District</th>
                                                    <th>Region</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var location in (List<RiskLocation>)ViewBag.lstRiskLocation)
                                                {
                                                <tr>
                                                    <td>@location.RiskName</td>
                                                    <td>@location.BuildingNo</td>
                                                    <td>@location.Street</td>
                                                    <td>@location.WardDescription</td>
                                                    <td>@location.TownDescription</td>
                                                    <td>@location.TownshipDescription</td>
                                                    <td>@location.DistrictDescription</td>
                                                    <td>@location.RegionDescription</td>
                                                </tr>
                                                }
                                            </tbody>
                                        </table>


                                    </div>
                                </div>
                            </div>
                        }


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>