AYASOMPO_SMSGatewayV2/Controllers/SetupController.cs
using System.Linq;
using System.Threading.Tasks;
using AYASOMPO_SMSGatewayV2.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System;

namespace AYASOMPO_SMSGatewayV2.Controllers
{
    public class SetupController : Controller
    {
        MainDBContext _db = new MainDBContext();
        private IHostingEnvironment _env;
        Common common = new Common();
        public ISession session;
        public IConfigurationRoot Configuration { get; }

        public SetupController(IHostingEnvironment env)
        {
            _env = env;
            var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
             .AddJsonFile("appsettings.json");
            Configuration = builder.Build();
        }

        #region SMS Format
        public IActionResult SMSFormat()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            ViewBag.SMSFormatList = _db.Category.OrderByDescending(d => d.Description).ToList();
            return View();
        }

        public IActionResult SaveSMSTempFormat(Category category)
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            if (category.Id == Guid.Empty)
            {
                category.Id = Guid.NewGuid();
                category.Status = category.Status;
                _db.Entry(category).State = EntityState.Added;
                _db.SaveChanges();
                TempData["Message"] = "Save Successful.";
                return RedirectToAction("SMSFormat");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    Category updatecategory = new Category();
                    updatecategory = _db.Category.Where(c => c.Id == category.Id).FirstOrDefault();
                    updatecategory.Description = category.Description;
                    updatecategory.MsgTemplate = category.MsgTemplate;
                    updatecategory.Status = category.Status;
                    updatecategory.RenewalFlag = category.RenewalFlag;

                    _db.Update(updatecategory);
                    _db.SaveChanges();
                    TempData["Message"] = "Update Successful.";
                    return RedirectToAction("SMSFormat");
                }
                return RedirectToAction("SMSFormat");
            }
        }
        public IActionResult EditSMSFormat(Guid Id)
        {
            try
            {
                if (!CheckLoginUser())
                    return RedirectToAction("Login", "Account");

                Category category = _db.Category.Where(r => r.Id == Id).FirstOrDefault();
                ViewBag.SMSFormatList = _db.Category.OrderByDescending(d => d.Description).ToList();
                return View("SMSFormat", category);
            }
            catch (Exception ex)
            {
                return View();
            }


        }

        #endregion

        #region Common Functions
        public bool CheckLoginUser()
        {
            if (HttpContext.Session.GetString("userId") == null)
                return false;
            return true;
        }

        #endregion

        #region UW Rule Set up 
        public IActionResult RuleSetup()
        {
            return View();
        }
        #endregion
    }
}

AYASOMPO_SMSGatewayV2/Views/Setup/RuleSetup.cshtml
@{
    ViewData["Title"] = "RuleSetup";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v5.15.4/css/all.css">
@*<link href="~/vendors/font-awesome/css/v5.15.4/font-awesome.css" rel="stylesheet" />*@
<div class="row">
    <div class="col-md-12">
        <div class="x_content">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Rule Base Register <small></small></h2>
                                <ul class="nav navbar-right panel_toolbox">
                                    <li>
                                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                    </li>

                                    <li>
                                        <a class="close-link"><i class="fa fa-close"></i></a>
                                    </li>
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">

                                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6">
                                    <div class="tile-stats">
                                        <div class="icon">
                                            <i class="fa fa-fire" style="color:#1ABB9C;"></i>
                                        </div>
                                        <div class="count">Fire</div>
                                        <p>Motor Underwritting Rules Set up</p>
                                        <h5 style="padding:10px;">
                                            <input type="button" value="Start" onclick="location.href='@Url.Action("FireRuleSetup", "FireRuleBase")'" class="btn btn-round btn-success" />
                                        </h5>

                                        @*<a href="#" class="form-control btn btn-info" style="margin-top:5px;"> Detail </a>*@
                                    </div>
                                </div>

                                <div class="animated flipInY col-lg-3 col-md-3 col-sm-6">
                                    <div class="tile-stats">
                                        <div class="icon">
                                            <i class="fa fa-car" style="color:#1ABB9C;"></i>
                                        </div>
                                        <div class="count">Motor</div>
                                        <p>Motor Underwritting Rules Set up</p>
                                        <h5 style="padding:10px;">
                                            <input type="button" value="Start" onclick="location.href='@Url.Action("MotorRuleSetup", "MotorRuleBase")'" class="btn btn-round btn-success" />
                                        </h5>

                                        @*<a href="#" class="form-control btn btn-info" style="margin-top:5px;"> Detail </a>*@
                                    </div>
                                </div>



                            </div>
                        </div>
                    </div>
                </div>
        </div>

    </div>
</div>

AYASOMPO_SMSGatewayV2/Views/Setup/SMSFormat.cshtml
@model Category
@{
    ViewData["Title"] = "SMSFormat";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>SMS template format </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <div class="row">

                    @if (TempData["Message"] != null)
                    {
                        <script type="text/javascript">
                            window.onload = function () {
                                $('#divMsg').show();
                            };
                        </script>
                    }

                    <div id="divMsg" class="alert alert-info col-md-12" style="display:none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">
                            &times;
                        </a>

                        <i class="fa fa-info-circle" style="font-size:16px;"></i>
                        <strong>@TempData["Message"]</strong>
                    </div>

                </div>


                @using (Html.BeginForm("SaveSMSTempFormat", "Setup", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <div class="form-horizontal form-label-left">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group row ">
                        <label class="control-label col-md-3 col-sm-3 ">Template Name</label>
                        <div class="col-md-9 col-sm-9 ">
                            <input type="text" class="form-control" asp-for="Description" placeholder="Template Name">
                        </div>
                    </div>

                    <div class="form-group row ">
                        <label class="control-label col-md-3 col-sm-3 ">Message</label>
                        <div class="col-md-9 col-sm-9 ">
                            <textarea type="text" class="form-control" style="min-height:200px !important;" asp-for="MsgTemplate" placeholder=""></textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-sm-3  control-label">
                            Active Status
                            <br>
                        </label>

                        <div class="col-md-9 col-sm-9 ">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" asp-for="Status"> Active
                                </label>
                            </div>
                        </div>

                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-sm-3  control-label">
                            Renewal case create flag
                            <br>
                            <small class="text-navy red">User should open/check renewal status for only renewal case create in CRM</small>
                        </label>

                        <div class="col-md-9 col-sm-9 ">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" asp-for="RenewalFlag"> Renewal flag
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9  offset-md-3">
                            <button type="button" class="btn btn-default btnayas-style" onclick="location.href='@Url.Action("SMSFormat", "Setup")'">
                                <i class="fa fa-refresh"></i>
                                Clear Form
                            </button>

                            <button type="submit" class="btn btn-primary btnayas-style">
                                <i class="fa fa-save"></i>
                                Save
                            </button>
                        </div>
                    </div>


                </div>
                }


            </div>
           
            <div class="card-box table-responsive">
                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Active</th>
                            <th>Renewal Flag</th>
                            <th>Template Name</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in (List<Category>)ViewBag.SMSFormatList)
                        {
                            <tr>
                                <td style="width:50px;">
                                    <a href='@Url.Action("EditSMSFormat", "Setup", new { @Id = @category.Id })'>
                                        <span class="fa fa-edit ayascolor"></span>
                                    </a>
                                </td>
                                <td style="width:50px;">@Html.CheckBox("chkActive", @category.Status, new { @disabled = "disabled" })</td>
                                <td style="width:50px;">@Html.CheckBox("chkRenewal", @category.RenewalFlag, new { @disabled = "disabled" })</td>
                                <td style="width:100px;">@category.Description</td>
                                <td style="width:300px;">@category.MsgTemplate</td>
                            </tr>
                        }

                    </tbody>
                </table>

            </div>
        </div>
    </div>

   
</div>