AYASOMPO_SMSGatewayV2/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using AYASOMPO_SMSGatewayV2.Models;
using AYASOMPO_SMSGatewayV2.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;

namespace AYASOMPO_SMSGatewayV2.Controllers
{
    public class ReportController : Controller
    {
        MainDBContext _db = new MainDBContext();
        JWTDataContext _JWTDataContext = new JWTDataContext();
        private IHostingEnvironment _env;
        public ISession _session;
        Common common = new Common();
        DataServices dataService = new DataServices();
        SmsService SmsService = new SmsService();
        CRMAPIService cRMAPIService = new CRMAPIService();
        private HttpClient _client;
        public IConfigurationRoot Configuration { get; }

        Survey_DBContext _Surveydb = new Survey_DBContext();

        private const string Alphabet = "23456789bcdfghjkmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ-_";
        private static readonly int Base = Alphabet.Length;

        public ReportController(IHostingEnvironment env)
        {
            _env = env;

            var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
             .AddJsonFile("appsettings.json");
            Configuration = builder.Build();

            _client = new HttpClient();
            string url = Configuration["InternalMiddleware:IPAddress"].ToString();
            _client.BaseAddress = new Uri(Configuration["InternalMiddleware:IPAddress"].ToString());
            _client.DefaultRequestHeaders.Clear();
            _client.DefaultRequestHeaders.Accept.Clear();
            _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        #region Success Renewal Sent SMS

        public IActionResult RenewalSMSbyStaff()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            SentSmsVM model = new SentSmsVM();
            ViewBag.StaffList = new SelectList(_db.SysUser.OrderBy(d => d.Name).ToList(), "Id", "Name");

            //model.StaffList = GetStaffData();
            //model.DepartmentList = GetDeptList();

            return View(model);
        }

        //[HttpPost]
        public IActionResult SentSMSReportData(SentSmsVM model)
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            SentSmsVM output = new SentSmsVM();
            if (model.FromDate == null && model.ToDate == null)
            {
                return RedirectToAction("RenewalSMSbyStaff");
            }
            else
            {
                output = SendSMSBySysId(model);
            }

            output.StaffList = GetStaffData();
            output.DepartmentList = GetDeptList();

            ViewBag.output = output;
            ViewBag.StaffList = new SelectList(_db.SysUser.Where(s => s.IsActive == true).OrderBy(d => d.Name).ToList(), "Id", "Name");
            HttpContext.Session.SetComplexData("lstSentSmsVM", output);
            return View("RenewalSMSbyStaff", output);
        }

        SentSmsVM SendSMSBySysId(SentSmsVM model)
        {
            SentSmsVM output = new SentSmsVM();
            try
            {
                //if (model.Status == "fail")
                //{
                //    model.ActivitiesFlag = false;
                //}
                //else
                //{
                //    model.ActivitiesFlag = true;
                //}
                //output.lst = (from u in _db.SysUser
                //              join sms in _db.SentSms on u.Id equals sms.SysId
                //              join d in _db.Department on u.Department equals d.Id
                //              //where d.IsDelete == false
                //              where u.Id == model.StaffId
                //              where sms.SentDate >= model.fromDate
                //              where sms.SentDate <= model.toDate.AddHours(23.50)
                //              where sms.ActivitiesFlag == model.ActivitiesFlag
                //              orderby sms.SentDate ascending
                //              select new SentSmsVM
                //              {
                //                  Id = sms.Id,
                //                  PhoneNumber = sms.PhoneNumber,
                //                  UserName = sms.UserName,
                //                  Message = sms.Message,
                //                  SentDate = sms.SentDate,
                //                  Smscount = sms.Smscount
                //              }).Distinct().ToList();

                if (model.StaffId != Guid.Empty)
                {
                    output.lst = (from sms in _db.SentSms
                                  where sms.SentDate >= model.fromDate
                                  where sms.SentDate <= model.toDate.AddHours(23.50)
                                  where sms.SysId == model.StaffId
                                  where sms.Channel == "RenewalNotice" &&  sms.Smsflag == "1"
                                  orderby sms.SentDate descending
                                  select new SentSmsVM
                                  {
                                      Id = sms.Id,
                                      PhoneNumber = sms.PhoneNumber,
                                      UserName = sms.UserName,
                                      Message = sms.Message,
                                      SentDate = sms.SentDate,
                                      Smscount = sms.Smscount,
                                      VehicleNo = sms.VehicleNo,
                                      PolicyNo = sms.PolicyNo,
                                      Category = sms.Channel
                                  }).Distinct().ToList();
                }
                else
                {
                    output.lst = (from sms in _db.SentSms
                                  where sms.SentDate >= model.fromDate
                                  where sms.SentDate <= model.toDate.AddHours(23.50)
                                  where sms.Channel == "RenewalNotice" && sms.Smsflag == "1"
                                  orderby sms.SentDate descending
                                  select new SentSmsVM
                                  {
                                      Id = sms.Id,
                                      PhoneNumber = sms.PhoneNumber,
                                      UserName = sms.UserName,
                                      Message = sms.Message,
                                      SentDate = sms.SentDate,
                                      Smscount = sms.Smscount,
                                      VehicleNo = sms.VehicleNo,
                                      PolicyNo = sms.PolicyNo,
                                      Category = sms.Channel
                                  }).Distinct().ToList();
                }

                output.StaffName = _db.SysUser.Where(u => u.Id == model.StaffId).Select(u => u.Name).FirstOrDefault();
                output.fromDate = model.fromDate;
                output.toDate = model.toDate;
                output.Status = model.Status;
                output.StaffId = model.StaffId;

                return output;
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public IActionResult ExportReportBySysId(SentSmsVM model)
        {
            SentSmsVM VM = new SentSmsVM();
            List<SentSmsVM> lstSentSmsVM = new List<SentSmsVM>();
            if (HttpContext.Session.GetObjectFromJson<SentSmsVM>("lstSentSmsVM") != null)
            {
                VM = HttpContext.Session.GetObjectFromJson<SentSmsVM>("lstSentSmsVM");
                //VM.lst = lstSentSmsVM;
            }
            else
            {
                VM = SendSMSBySysId(model);
                if (VM == null)
                {
                    TempData["Message"] = "Invalid Request. Please preview data that you want to download.";
                    return RedirectToAction("RenewalSMSbyStaff");
                }
            }

            var columnHeader = new List<string>
            {
                "Sent Date/Time",
                "Receiver's Name",
                "Phone Number",
                "Vehicle No",
                "Invoice No",
                "Template",
                "Message"
            };

            var fileContent = ExportExcelBySysId(VM, columnHeader, "SentSMS ByStaff");
            return File(fileContent, "application/ms-excel", "Sent SMS Report  By Staff.xlsx");
        }

        public byte[] ExportExcelBySysId(SentSmsVM VM, List<string> columnHeader, string heading)
        {
            byte[] result = null;
            using (ExcelPackage package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add(heading);
                worksheet.DefaultColWidth = 20;

                worksheet.Cells[1, 1].Style.Font.Bold = true;
                worksheet.Cells[1, 1].Value = "Staff Name :";
                worksheet.Cells[1, 2].Value = VM.StaffName;

                worksheet.Cells[2, 1].Style.Font.Bold = true;
                worksheet.Cells[2, 1].Value = "From Date :";
                worksheet.Cells[2, 2].Value = string.Format("{0:dd/MM/yyyy}", VM.fromDate);

                worksheet.Cells[3, 1].Style.Font.Bold = true;

AYASOMPO_SMSGatewayV2/Views/Report/BulkSmsByStaff.cshtml
@model SentSmsVM
@{
    ViewData["Title"] = "BulkSmsByStaff";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script>

    $(function () {
        $(".datepicker").datetimepicker({
            format: "DD/MMM/YYYY"
        });
    });

</script>
<link href="~/css/loading.css" rel="stylesheet" />
<script src="~/js/smsjs.js"></script>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Report By Bulk</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a href='@Url.Action("ExportBulkSmsReportBySysId", "Report")'><i class="fa fa-file-excel-o" style="color:#CE123C;"></i></a>
                    </li>
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>

                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />

                <div class="row">

                    @if (TempData["Message"] != null)
                    {
                        <script type="text/javascript">
                            window.onload = function () {
                                $('#divMsg').show();
                            };
                        </script>
                    }

                    <div id="divMsg" class="alert alert-info col-md-12" style="display:none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">
                            &times;
                        </a>

                        <i class="fa fa-info-circle" style="font-size:16px;"></i>
                        <strong>@TempData["Message"]</strong>
                    </div>

                </div>


                @using (Html.BeginForm("SentBulkSMSReportData", "Report", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-horizontal form-label-left">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="control-label col-md-4 col-sm-4">From Date <span style="color:red;">*</span></label>
                                <div class="col-md-8 col-sm-8 ">
                                    <input class="form-control datepicker" type="text" asp-for="fromDate" id="fromdate" placeholder="From Date" required />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-md-4 col-sm-4">Template <span style="color:red;">*</span></label>
                                <div class="col-md-8 col-sm-8">
                                    <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.CategoryList" placeholder="Select Category" required>
                                        <option>Select Category</option>
                                    </select>

                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group row">
                                <label class="control-label col-md-4 col-sm-4">To Date <span style="color:red;">*</span></label>
                                <div class="col-md-8 col-sm-8 ">
                                    <input class="form-control datepicker" type="text" asp-for="toDate" id="todate" placeholder="To Date" required />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-md-4 col-sm-4">Staff Name</label>
                                <div class="col-md-8 col-sm-8">
                                    @*<select class='form-control' name="StaffId" id="select1">
                                        <option value="">Select </option>
                                        @foreach (var staff in Model.StaffList)
                                        {
                                            <option value="@staff.Id">@staff.Name</option>
                                        }

                                    </select>*@
                                    <select asp-for="StaffId" class="form-control" asp-items="@ViewBag.StaffList" placeholder="Select">
                                        <option>Select</option>
                                    </select>

                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-9 col-sm-9  offset-md-4">
                                <button type="button" class="btn btn-default btnayas-style" onclick="location.href='@Url.Action("BulkSmsByStaff", "Report")'">
                                    <i class="fa fa-refresh"></i>
                                    Clear Form
                                </button>
                                <button type="submit" class="btn btn-primary btnayas-style">
                                    <i class="fa fa-eye"></i>
                                    Preview
                                </button>

                            </div>
                        </div>
                    </div>
                }

            </div>

            <div class="card-box table-responsive">
                @if (Model.CategoryId == Guid.Parse("019a983a-4323-4b12-9023-109cfd47c0e8"))
                {
                    <table id="tblOP" class="table table-striped table-bordered dt-responsive datatable-responsive nowrap" cellspacing="0" style="width: 100%;">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Sent Date</th>
                                <th>Receiver Name</th>
                                <th>Phone Number</th>
                                <th>Vehicle No</th>
                                <th>Invoice No</th>
                                <th>Template</th>
                                <th>Message</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (ViewBag.output != null)
                            {
                                @foreach (var sms in (List<SentSmsVM>)ViewBag.output)
                                {
                            <tr>
                                <td style="width:5px;"></td>
                                <td style="width:100px;">@sms.SentDate</td>
                                <td style="width:50px;">@sms.UserName</td>
                                <td style="width:100px;">@sms.PhoneNumber</td>
                                <td style="width:50px;">@sms.VehicleNo</td>
                                <td style="width:100px;">@sms.PolicyNo</td>
                                <td style="width:100px;">@sms.Category</td>
                                <td style="width:100px;">@sms.Message</td>
                            </tr>
                                }
                            }


                        </tbody>
                    </table>
                }
                else
                {
                    <table id="tblOP" class="table table-striped table-bordered dt-responsive datatable-responsive nowrap" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Sent Date</th>
                                <th>Receiver Name</th>
                                <th>Phone Number</th>
                                <th>Vehicle No</th>
                                <th>Policy No</th>
                                <th>Template</th>
                                <th>Message</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (ViewBag.output != null)
                            {
                                @foreach (var sms in (List<SentSmsVM>)ViewBag.output)
                                {
                                    <tr>
                                        <td style="width:5px;"></td>
                                        <td style="width:100px;">@sms.SentDate</td>
                                        <td style="width:100px;">@sms.UserName</td>
                                        <td style="width:100px;">@sms.PhoneNumber</td>
                                        <td style="width:100px;">@sms.VehicleNo</td>
                                        <td style="width:100px;">@sms.PolicyNo</td>
                                        <td style="width:100px;">@sms.Category</td>
                                        <td style="width:100px;">@sms.Message</td>
                                    </tr>
                                }
                            }


                        </tbody>
                    </table>
                }

            </div>
        </div>
    </div>


</div>

AYASOMPO_SMSGatewayV2/Views/Report/CustomRenewalFailCase.cshtml
@model TempRenewalCaseCreate
@{
    ViewData["Title"] = "CustomRenewalFailCase";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script src="~/js/smsjs.js"></script>
<script>

    $(function () {
        $(".monthpicker").datetimepicker({
            format: "MMM/YYYY"
        });
    });

</script>

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Create Renewal Case By OP</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a href='@Url.Action("ExportReportCustomerFailCase", "Report")'><i class="fa fa-file-excel-o"  style="color:#CE123C"></i></a>
                    </li>

                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>

                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">
                <br />
                @*<div class="row">

                        @if (TempData["Message"] != null)
                        {
                            <script type="text/javascript">
                                window.onload = function () {
                                    $('#divMsg').show();
                                };
                            </script>
                        }

                        <div id="divMsg" class="alert alert-info col-md-12" style="display:none;">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">
                                &times;
                            </a>

                            <i class="fa fa-info-circle" style="font-size:16px;"></i>
                            <strong>@TempData["Message"]</strong>
                        </div>

                    </div>*@


                @using (Html.BeginForm("GetCustomRenewalFailCase", "Report", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <div class="form-horizontal form-label-left">
                    <div class="form-group col-md-6">
                        <label class="control-label col-md-3 col-sm-3 ">From Date</label>
                        <div class="col-md-8 col-sm-8 ">
                            <input class="form-control" type="date" asp-for="FromDate" placeholder="From Date" required />
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="control-label col-md-3 col-sm-3 ">To Date</label>
                        <div class="col-md-8 col-sm-8 ">
                            <input class="form-control" type="date" asp-for="ToDate" placeholder="To Date" required />
                        </div>
                    </div>

                    <div class="clearfix"></div>
                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-md-9 col-sm-9  offset-md-3">
                            <button type="submit" class="btn btn-default btnayas-style">
                                <i class="fa fa-upload"></i>
                                Preview
                            </button>

                        </div>
                    </div>

                    
                </div>

                    <div class="card-box table-responsive">
                        @if (ViewBag.lsttempRenewalCase != null)
                        {
                            <table id="tblOP" class="table table-striped table-bordered dt-responsive datatable-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Created Date</th>
                                        <th>Phone Number</th>
                                        <th>Customer Name</th>
                                        <th>Invoice No</th>
                                        <th>Risk Name</th>
                                        <th>Expired Date</th>

                                        <th>Renewal Premium</th>
                                        <th>Product</th>
                                        <th>From Date</th>
                                        <th>To Date</th>
                                        <th>Link</th>

                                        <th>Customer Code</th>
                                        <th>Month</th>
                                        <th>PersonInCharge</th>
                                        <th>Responsiable Party</th>
                                        <th>Policy Number</th>

                                        <th>Branch</th>
                                        <th>Intermediary Type</th>
                                        <th>Agent Code</th>
                                        <th>Agent Name</th>
                                        <th>Account Code</th>

                                        <th>Authorized Code</th>
                                        <th>Authorized Name</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var motor in (List<TempRenewalCaseCreate>)ViewBag.lsttempRenewalCase)
                                    {
                                    <tr>
                                        <td style="width:5px;"></td>
                                        <td style="width:100px;">@motor.CreatedDate</td>
                                        <td style="width:100px;">@motor.PhoneNumber</td>
                                        <td style="width:100px;">@motor.CustomerName</td>
                                        <td style="width:100px;">@motor.InvoiceNo</td>
                                        <td style="width:100px;">@motor.RiskName</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ExpiryDate)</td>

                                        <td style="width:100px;">@motor.RenewalPremium</td>
                                        <td style="width:300px;">@motor.Product</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.FromDate)</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ToDate)</td>
                                        <td style="width:100px;">@motor.Link</td>

                                        <td style="width:300px;">@motor.CusCode</td>
                                        <td style="width:300px;">@motor.Month</td>
                                        <td style="width:300px;">@motor.PersonInCharge</td>
                                        <td style="width:300px;">@motor.ResponsibleParty</td>
                                        <td style="width:300px;">@motor.PolicyNo</td>

                                        <td style="width:100px;">@motor.Branch</td>
                                        <td style="width:300px;">@motor.IntermediaryType</td>
                                        <td style="width:300px;">@motor.AgentCode</td>
                                        <td style="width:300px;">@motor.AgentName</td>
                                        <td style="width:300px;">@motor.AccountCode</td>

                                        <td style="width:300px;">@motor.AuthorizedCode</td>
                                        <td style="width:100px;">@motor.AuthorizedName</td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        }
                    </div>
                }

            </div>
        </div>
    </div>


</div>