AYASOMPO_SMSGatewayV2/Controllers/SMSController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using OfficeOpenXml.Style;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using AYASOMPO_SMSGatewayV2.Models;
using AYASOMPO_SMSGatewayV2.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;

namespace AYASOMPO_SMSGatewayV2.Controllers
{
    public class SMSController : Controller
    {
        MainDBContext _db = new MainDBContext();
        JWTDataContext _JWTDataContext = new JWTDataContext();
        private IHostingEnvironment _env;
        Common common = new Common();
        public ISession session;
        public IConfigurationRoot Configuration { get; }
        private HttpClient _client;
        DataServices dataService = new DataServices();
        CRMAPIService cRMAPIService = new CRMAPIService();
        SmsService SmsService = new SmsService();

        public enum ApproveSendSMS
        {
            Pending,
            Send_SMS,
            No_SMS
        }

        public enum UwApproval
        {
            Approved_with_conditions,
            Approved,
            Decline,
            Policy_Cancel,
            Lapsed_Policy_Cancel
        }

        public enum Y_N_Condition
        {
            Yes,
            No
        }

        public enum DonePending
        {
            Done,
            Pending
        }

        public SMSController(IHostingEnvironment env)
        {
            _env = env;
            var builder = new ConfigurationBuilder()
             .SetBasePath(Directory.GetCurrentDirectory())
             .AddJsonFile("appsettings.json");
            Configuration = builder.Build();

            _client = new HttpClient();
            string url = Configuration["CoreMiddleware:IPAddress"].ToString();
            _client.BaseAddress = new Uri(Configuration["CoreMiddleware:IPAddress"].ToString());
            _client.DefaultRequestHeaders.Clear();
            _client.DefaultRequestHeaders.Accept.Clear();
            _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        public IActionResult Dashboard()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            ViewBag.TotalMotorCount = _db.MotorRenewalRegister.Count();
            ViewBag.TotalFireCount = _db.FireRenewalRegister.Count();
            List<SummaryRenewalRegister> lstSummaryRenewalRegister = new List<SummaryRenewalRegister>();
            lstSummaryRenewalRegister = dataService.GetSummaryRenewalRegister();

            ViewBag.lstMotorSummaryRenewalRegister = lstSummaryRenewalRegister.Where(m=> m.productclass== "MOTOR INSURANCE").ToList();
            ViewBag.lstFireSummaryRenewalRegister = lstSummaryRenewalRegister.Where(m => m.productclass == "FIRE INSURANCE").ToList();
            ViewBag.lstHealthSummaryRenewalRegister = lstSummaryRenewalRegister.Where(m => m.productclass == "HEALTH INSURANCE").ToList();
            ViewBag.lstPASummaryRenewalRegister = lstSummaryRenewalRegister.Where(m => m.productclass == "PERSONAL ACCIDENT INSURANCE").ToList();
            ViewBag.lstENGGSummaryRenewalRegister = lstSummaryRenewalRegister.Where(m => m.productclass == "ENGINEERING").ToList();
            ViewBag.lstPropertySummaryRenewalRegister = lstSummaryRenewalRegister.Where(m => m.productclass == "PROPERTY").ToList();
            return View();
        }

        public IActionResult RenewalCaseDashboard()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            return View();
        }

        #region Data Sync
        public IActionResult RenewalDataSync()
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            filterRenewalDataModel filterRenewalData = new filterRenewalDataModel();
            PrepareData();
            return View(filterRenewalData);
        }
        
        [HttpPost]
        public async Task<IActionResult> RenewalDataSync(filterRenewalDataModel filterRenewalData)
        {
            if (!CheckLoginUser())
                return RedirectToAction("Login", "Account");

            PrepareData();
            try
            {
                if (filterRenewalData.month == null || filterRenewalData.classname == null)
                {
                    TempData["Message"] = "Invalid request data";
                    return View("RenewalDataSync");
                }

                var firstDayOfMonth = new DateTime(filterRenewalData.month.Year, filterRenewalData.month.Month, 1);
                var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);
                
                if (filterRenewalData.classname == "FI")
                {
                    List<FireRenewalRegister> lstFireRenewalRegisters = new List<FireRenewalRegister>();
                    lstFireRenewalRegisters = await GetFireRenewalRegisterAsync(filterRenewalData);
                    ViewBag.lstFireRenewalRegisters = lstFireRenewalRegisters;
                    var fireRenewalRegisterlist = (from fire in _db.FireRenewalRegister
                                                   where Convert.ToDateTime(fire.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date
                                                   where Convert.ToDateTime(fire.ExpiryDate).Date <= Convert.ToDateTime(lastDayOfMonth).Date
                                                   select fire).ToList();
                  
                    if (fireRenewalRegisterlist.Count() == 0)
                    {
                        SaveFireRenewalRegister(lstFireRenewalRegisters);
                        var motorRenewalRegister = (from fire in _db.FireRenewalRegister
                                                    where Convert.ToDateTime(fire.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date
                                                    where Convert.ToDateTime(fire.ExpiryDate).Date <= Convert.ToDateTime(lastDayOfMonth).Date
                                                    select fire).ToList();

                        TempData["SyncMessage"] = "Fire Data Sync is success for total " + motorRenewalRegister.Count() + " transactions.";
                    }
                    else
                    {
                        TempData["SyncMessage"] = "Already fire data sync for " + Convert.ToDateTime(filterRenewalData.month).ToString("MMMM");
                    }
                }
                else if(filterRenewalData.classname == "MT")
                {
                    List<MotorRenewalRegister> lstMotorRenewalRegisters = new List<MotorRenewalRegister>();
                    lstMotorRenewalRegisters = await GetMotorRenewalRegisterAsync(filterRenewalData);
                    ViewBag.lstMotorRenewalRegisters = lstMotorRenewalRegisters;
                    var motorRenewalRegisterlist = (from motor in _db.MotorRenewalRegister
                                                    where Convert.ToDateTime(motor.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date
                                                    where Convert.ToDateTime(motor.ExpiryDate).Date <= Convert.ToDateTime(lastDayOfMonth).Date
                                                    select motor).ToList();


                    if (motorRenewalRegisterlist.Count() == 0)
                    {
                        SaveMotorRenewalRegister(lstMotorRenewalRegisters);
                        var motorRenewalRegister = (from motor in _db.MotorRenewalRegister
                                                    where Convert.ToDateTime(motor.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date
                                                    where Convert.ToDateTime(motor.ExpiryDate).Date <= Convert.ToDateTime(lastDayOfMonth).Date
                                                    select motor).ToList();

                        TempData["SyncMessage"] = "Motor Data Sync is success for total " + motorRenewalRegister.Count() + " transactions.";
                    }
                    else
                    {
                        TempData["SyncMessage"] = "Already motor data sync for " + Convert.ToDateTime(filterRenewalData.month).ToString("MMMM");
                    }
                }
                else if(filterRenewalData.classname == "LF")
                {
                    List<HealthRenewalRegister> lstHealthRenewalRegisters = new List<HealthRenewalRegister>();
                    lstHealthRenewalRegisters = await GetHealthRenewalRegisterAsync(filterRenewalData);
                    ViewBag.lstHealthRenewalRegisters = lstHealthRenewalRegisters;
                    var healthRenewalRegisterlist = (from health in _db.HealthRenewalRegister
                                                    where Convert.ToDateTime(health.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date
                                                    where Convert.ToDateTime(health.ExpiryDate).Date <= Convert.ToDateTime(lastDayOfMonth).Date
                                                    select health).ToList();


                    if (healthRenewalRegisterlist.Count() == 0)
                    {
                        SaveHealthRenewalRegister(lstHealthRenewalRegisters);
                        var healthRenewalRegister = (from health in _db.HealthRenewalRegister
                                                    where Convert.ToDateTime(health.ExpiryDate).Date >= Convert.ToDateTime(firstDayOfMonth).Date

AYASOMPO_SMSGatewayV2/Views/SMS/Dashboard.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}
<link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v5.15.4/css/all.css">
@*<link href="~/vendors/font-awesome/css/v5.15.4/font-awesome.css" rel="stylesheet" />*@

AYASOMPO_SMSGatewayV2/Views/SMS/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<h1>Index</h1>

AYASOMPO_SMSGatewayV2/Views/SMS/RenewalCaseCreateWithoutSMS.cshtml
@{
    ViewData["Title"] = "RenewalCaseCreateWithoutSMS";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Create Renewal Case By OP</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>

            <div class="x_content">
                <br />
                <div class="row">

                    @if (TempData["Message"] != null)
                    {
                        <script type="text/javascript">
                            window.onload = function () {
                                $('#divMsg').show();
                            };
                        </script>
                    }

                    <div id="divMsg" class="alert alert-info col-md-12" style="display:none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">
                            &times;
                        </a>

                        <i class="fa fa-info-circle" style="font-size:16px;"></i>
                        <strong>@TempData["Message"]</strong>
                    </div>

                </div>


                @using (Html.BeginForm("CreateCustomRenewalCase", "SMS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <div class="form-horizontal form-label-left">
                    <div class="col-md-6">
                        <div class="col-md-9 col-sm-9 ">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="chkSentSMS" value="true" name="chkSentSMS"> Sent SMS
                                </label>
                            </div>
                        </div>

                    </div>

                    <div class="clearfix"></div>
                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-md-9 col-sm-9  offset-md-3">
                            <button type="submit" class="btn btn-default btnayas-style">
                                <i class="fa fa-upload"></i>
                                Create Case
                            </button>

                        </div>
                    </div>
                </div>

                    <div class="card-box table-responsive">
                        @if (ViewBag.lstTempRenewalCaseCreate != null)
                        {
                            <table id="tblOP" class="table table-striped table-bordered dt-responsive datatable-responsive nowrap" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Phone Number</th>
                                        <th>Customer Name</th>
                                        <th>Invoice No</th>
                                        <th>Risk Name</th>
                                        <th>Expired Date</th>

                                        <th>Renewal Premium</th>
                                        <th>Product</th>
                                        <th>From Date</th>
                                        <th>To Date</th>
                                        <th>Link</th>

                                        <th>Customer Code</th>
                                        <th>Month</th>
                                        <th>PersonInCharge</th>
                                        <th>Responsiable Party</th>
                                        <th>Policy Number</th>

                                        <th>Branch</th>
                                        <th>Intermediary Type</th>
                                        <th>Agent Code</th>
                                        <th>Agent Name</th>
                                        <th>Account Code</th>

                                        <th>Authorized Code</th>
                                        <th>Authorized Name</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var motor in (List<TempRenewalCaseCreate>)ViewBag.lstTempRenewalCaseCreate)
                                    {
                                    <tr>
                                        <td style="width:100px;">@motor.PhoneNumber</td>
                                        <td style="width:100px;">@motor.CustomerName</td>
                                        <td style="width:100px;">@motor.InvoiceNo</td>
                                        <td style="width:100px;">@motor.RiskName</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ExpiryDate)</td>

                                        <td style="width:100px;">@motor.RenewalPremium</td>
                                        <td style="width:300px;">@motor.Product</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.FromDate)</td>
                                        <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ToDate)</td>
                                        <td style="width:100px;">@motor.Link</td>

                                        <td style="width:300px;">@motor.CusCode</td>
                                        <td style="width:300px;">@motor.Month</td>
                                        <td style="width:300px;">@motor.PersonInCharge</td>
                                        <td style="width:300px;">@motor.ResponsibleParty</td>
                                        <td style="width:300px;">@motor.PolicyNo</td>

                                        <td style="width:100px;">@motor.Branch</td>
                                        <td style="width:300px;">@motor.IntermediaryType</td>
                                        <td style="width:300px;">@motor.AgentCode</td>
                                        <td style="width:300px;">@motor.AgentName</td>
                                        <td style="width:300px;">@motor.AccountCode</td>

                                        <td style="width:300px;">@motor.AuthorizedCode</td>
                                        <td style="width:100px;">@motor.AuthorizedName</td>
                                    </tr>
                                    }

                                </tbody>
                            </table>
                        }
                    </div>
                 }

                    </div>
                </div>
    </div>


</div>

AYASOMPO_SMSGatewayV2/Views/SMS/RenewalDataSync.cshtml
@model filterRenewalDataModel
@{
    ViewData["Title"] = "RenewalDataSync";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script>
    
    $(function () {
        $(".monthpicker").datetimepicker({
            format: "MMM/YYYY"
        });
    });

</script>
<link href="~/css/loading.css" rel="stylesheet" />
<script src="~/js/smsjs.js"></script>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Generate Monthly Renewal Notice</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <div class="row">

                    @if (TempData["Message"] != null)
                    {
                        <script type="text/javascript">
                            window.onload = function () {
                                $('#divMsg').show();
                            };
                        </script>
                    }

                    <div id="divMsg" class="alert alert-info col-md-12" style="display:none;">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">
                            &times;
                        </a>

                        <i class="fa fa-info-circle" style="font-size:16px;"></i>
                        <strong>@TempData["Message"]</strong>
                    </div>

                </div>


                @using (Html.BeginForm("RenewalDataSync", "SMS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                <div class="form-horizontal form-label-left">
                    <div class="form-group row ">
                        <label class="control-label col-md-3 col-sm-3 ">Month</label>
                        <div class="col-md-9 col-sm-9 ">
                            @*<input type="date" class="date-picker form-control" asp-for="month" placeholder="Month">*@
                            <input class="form-control monthpicker" type="text" asp-for="month" id="month" placeholder="mmm/yyyy" required />
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="control-label col-md-3 col-sm-3 ">Product</label>
                        <div class="col-md-9 col-sm-9 ">
                            @Html.DropDownListFor(model => model.classname, ViewBag.ProductClass as IEnumerable<SelectListItem>, "Select Product", new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9  offset-md-3">
                            <button type="button" class="btn btn-default btnayas-style" onclick="location.href='@Url.Action("RenewalDataSync", "SMS")'">
                                <i class="fa fa-refresh"></i>
                                Clear Form
                            </button>

                            <button type="submit" id="btnSync" class="btn btn-primary btnayas-style">
                                <i class="fa fa-retweet"></i>
                                Sync Data
                            </button>
                        </div>
                    </div>


                </div>
                }

            </div>

            <div class="card-box table-responsive">

                <section id="brand">

                    @if (TempData["SyncMessage"] != null)
                    {
                        <script type="text/javascript">
                            window.onload = function () {
                                $('#divSyncMsg').show();
                            };
                        </script>
                    }


                    
                    <div class="alert alert-success" id="divSyncMsg" style="display:none;">
                        <h4><i class="fa fa-warning"></i> Save!</h4>
                        <strong style="font-size:16px;">@TempData["SyncMessage"]</strong>
                    </div>
                </section>
            </div>
        </div>
    </div>

</div>

<div id="mdlLoading" class="modal fade" role="dialog" data-backdrop="true" style="background:none !important;">
    <div class="modal-dialog modal-lg" style="background:none !important;">
        <!-- Modal content-->
        <div class="modal-body" style="min-height:400px;background-color:none !important;">
            <div class="container">
                <div class="row">
                    <div id="loader">
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="dot"></div>
                        <div class="lading"></div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

AYASOMPO_SMSGatewayV2/Views/SMS/RenewalNoSMSCase.cshtml
@model filterRenewalNoSMSCase;

@{
    ViewData["Title"] = "RenewalNoSMSCase";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
}

<script>

    $(function () {
        $(".datepicker").datetimepicker({
            format: "DD/MMM/YYYY"
        });
    });

</script>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Renewal No SMS Case</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li>
                        <a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />

                @using (Html.BeginForm("GetRenewalNoSMSCase", "SMS", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="form-horizontal form-label-left">
                        <div class="form-group row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-4 col-sm-4">From Date</label>
                                    <div class="col-md-8 col-sm-8 ">
                                        <input class="form-control datepicker" type="text" asp-for="filterFromDate" id="fromdate" placeholder="From Date" required />
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-4 col-sm-4">To Date</label>
                                    <div class="col-md-8 col-sm-8 ">
                                        <input class="form-control datepicker" type="text" asp-for="filterToDate" id="todate" placeholder="To Date" required />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <div class="form-group row">
                                    <label class="control-label col-md-4 col-sm-4">From Date</label>
                                    <div class="col-md-8 col-sm-8 ">
                                        @Html.DropDownListFor(model => model.classname, ViewBag.ProductClass as IEnumerable<SelectListItem>, "Select Product", new { @class = "form-control" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-9 col-sm-9  offset-md-3">

                                <button type="button" class="btn btn-default btnayas-style" onclick="location.href='@Url.Action("RenewalNoSMSCase", "SMS")'">
                                    <i class="fa fa-refresh"></i>
                                    Clear Form
                                </button>

                                <button type="submit" class="btn btn-primary btnayas-style">
                                    <i class="fa fa-eye"></i>
                                    Preview
                                </button>

                            </div>
                        </div>
                    </div>
                }

            </div>




            <div class="card-box table-responsive">
                <div>
                    <a href='@Url.Action("ExportRenewalNoSMSCase", "SMS", null)'>
                        <img src="~/images/excel-file.png" style="float:right;margin-bottom:10px;margin-right:10px;" />
                    </a>
                </div>
                <table id="tblOP" class="table table-striped table-bordered dt-responsive datatable-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Phone Number</th>
                            <th>Customer Name</th>
                            <th>Invoice No</th>
                            <th>Risk Name</th>
                            <th>Expired Date</th>
                            <th>Renewal Premium</th>
                            <th>Product</th>
                            <th>From Date</th>
                            <th>To Date</th>
                            <th>Link</th>
                            <th>Customer Code</th>
                            <th>Month</th>
                            <th>PersonInCharge</th>
                            <th>Responsiable Party</th>
                            <th>Policy Number</th>
                            <th>Branch</th>
                            <th>Intermediary Type</th>
                            <th>Agent Code</th>
                            <th>Agent Name</th>
                            <th>Account Code</th>
                            <th>Authorized Code</th>
                            <th>Authorized Name</th>
                            <th style="display:none;"></th>
                        </tr>
                    </thead>
                    <tbody>
                            @foreach (var motor in (List<SMSRenewalViewModel>)ViewBag.lstSMSRenewalViewModels)
                            {
                        <tr>
                            <td style="width:100px;">@motor.PhoneNumber</td>
                            <td style="width:100px;">@motor.CustomerName</td>
                            <td style="width:100px;">@motor.InvoiceNo</td>
                            <td style="width:100px;">@motor.RiskName</td>
                            <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ExpiryDate)</td>

                            <td style="width:100px;">@motor.RenewalPremium</td>
                            <td style="width:300px;">@motor.Class</td>
                            <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.FromDate)</td>
                            <td style="width:300px;">@String.Format("{0:MMM/dd/yy}", @motor.ToDate)</td>
                            <td style="width:300px;">@motor.Link</td>

                            <td style="width:300px;">@motor.CusCode</td>
                            <td style="width:300px;">@motor.Month</td>
                            <td style="width:300px;">@motor.PersonInCharge</td>
                            <td style="width:300px;">@motor.ResponsibleParty</td>
                            <td style="width:300px;">@motor.PolicyNo</td>

                            <td style="width:300px;">@motor.Branch</td>
                            <td style="width:300px;">@motor.IntermediaryType</td>
                            <td style="width:300px;">@motor.AgentCode</td>
                            <td style="width:300px;">@motor.AgentName</td>
                            <td style="width:300px;">@motor.AccountCode</td>

                            <td style="width:300px;">@motor.AuthorizedCode</td>
                            <td style="width:300px;">@motor.AuthorizedName</td>
                            <td style="width:50px;display:none !important;">
                                <input class="form-control hdfId" type="text" value="@motor.Id" readonly style="display:none !important;" />
                            </td>
                        </tr>
                            }


                    </tbody>
                </table>


            </div>
        </div>
    </div>


</div>